project_id = "jvrngbtknubhkfwvnkvd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://jvrngbtknubhkfwvnkvd.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation = true
security_password_length = 8
enable_signup = true

[edge_functions]
enabled = true
port = 54329

[functions.analyze-cattle]
verify_jwt = false