// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvrngbtknubhkfwvnkvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cm5nYnRrbnViaGtmd3Zua3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Mzk0MjQsImV4cCI6MjA3MjIxNTQyNH0.1AuFP97roym1QlHOO9YoZuGxSf5hbHZiMH_oEETvfj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});